<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Case-level idempotency for the reporting wizard.
 *
 * `evidence_items.idempotency_key` (Sprint 4) only dedups *within* a case, so
 * it cannot help the intake: a retried `POST /cases` after a dropped connection
 * creates a whole new case, and the evidence keys land on it harmlessly. The
 * duplicate the citizen actually causes is a duplicate accident.
 *
 * Scoped to the reporter rather than globally unique: the key is generated by
 * the client, and one user's collision must never be able to block another's
 * report.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('accident_cases', function (Blueprint $table) {
            $table->uuid('idempotency_key')->nullable()->after('case_no');
            $table->unique(['reported_by', 'idempotency_key']);
        });
    }

    public function down(): void
    {
        Schema::table('accident_cases', function (Blueprint $table) {
            $table->dropUnique(['reported_by', 'idempotency_key']);
            $table->dropColumn('idempotency_key');
        });
    }
};
